#!/bin/bash
#!/bin/bash
#$ -cwd
# error = Merged with joblog
#$ -o logs/joblog.$JOB_ID
#$ -j y
#$ -l h_rt=10:00:00,h_data=10G
#$ -l highp
# Email address to notify
#$ -M asxue@g.ucla.edu
# Notify when
#$ -m bea

cd /u/home/a/asxue
source .bashrc
conda activate colide-nv

python /u/home/a/asxue/project-hjp/dotears/workflow/scripts/run_naive.py \
            --data /u/home/a/asxue/project-hjp/dotears/gwps/top100.npz \
            --out /u/home/a/asxue/project-hjp/dotears/gwps/out/top100_colide-nv \
            --method colide-nv --lambda1 0.1