#!/bin/bash
#!/bin/bash
#$ -cwd
# error = Merged with joblog
#$ -o logs/joblog.$JOB_ID
#$ -j y
#$ -l h_rt=1:00:00,h_data=10G
#$ -l highp
# Email address to notify
#$ -M asxue@g.ucla.edu
# Notify when
#$ -m bea

cd /u/home/a/asxue
source .bashrc
conda activate std

Rscript /u/home/a/asxue/project-hjp/dotears/gwps/scripts/gies_repr.R \
	--data /u/home/a/asxue/project-hjp/dotears/gwps/top100_lognormal.npz \
        --out /u/home/a/asxue/project-hjp/dotears/gwps/out_lognormal/top100_gies
