p: 40
d: 0.2
k: 4
lower_edge_range: 0.3
upper_edge_range: 1.0
lower_std_range: 0.5
upper_std_range: 2.0
n_sims: 25
n: 100
a: 4
golem_lambda2_file: 'data/lambda2s.csv'
output_dir: 'data/p40_high_density_weak_effects'
n_folds: 5
