p: 20
d: 0.2
k: 2
lower_edge_range: 0.3
upper_edge_range: 0.5
lower_std_range: 0.5
upper_std_range: 2.0
n_sims: 10
n: 100
a: 4
golem_lambda2_file: 'data/lambda2s.csv'
output_dir: 'data/p20_low_density_weak_effects'
n_folds: 5
